In [ ]:


!pip install -q -U "tensorflow-text==2.9.*"

# Importing libraries
import numpy as np 
import pandas as pd
import tensorflow as tf

import spacy
import en_core_web_sm
nlp = en_core_web_sm.load()
from spacy.lang.en.stop_words import STOP_WORDS

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix


# Import Tensorflow & Pathlib librairies
import tensorflow as tf 
import pathlib 
import pandas as pd 
import os
import io
import warnings
from sklearn.model_selection import train_test_split
warnings.filterwarnings('ignore')

from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense, Embedding, GlobalMaxPool1D, BatchNormalization, GlobalAveragePooling1D
from tensorflow.keras.models import Sequential
from tensorflow.keras.losses import BinaryCrossentropy
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import BinaryAccuracy

from IPython.display import Image


     

In [ ]:
import plotly.io as pio
import plotly.express as px
import plotly.graph_objects as go
import plotly.offline as pyo
import plotly.offline as py
import plotly.tools as tls

In [ ]:
!python -m spacy download en_core_web_md -q

/usr/local/lib/python3.9/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
2023-04-03 07:29:12.109269: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 7.9 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')


In [ ]:
dataset = pd.read_csv("https://full-stack-bigdata-datasets.s3.eu-west-3.amazonaws.com/Deep+Learning/project/spam.csv", encoding =  "ISO-8859-1")

In [ ]:
# Displaying basic stats
print("Number of rows : {}".format(dataset.shape[0]))
print("Number of columns : {}".format(dataset.shape[1]))
print()
print()

print("Display of dataset: ")
display(dataset.head())
print()
print()

print("Basics statistics: ")
data_desc = dataset.describe(include='all')
display(data_desc)
print()
print()

print("Percentage of missing values: ")
display(100*dataset.isnull().sum()/dataset.shape[0])
print()
print()

print("Infos")
display(dataset.info())


Number of rows : 5572
Number of columns : 5


Display of dataset: 


v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN



Basics statistics: 


v1                      v2  \
count   5572                    5572   
unique     2                    5169   
top      ham  Sorry, I'll call later   
freq    4825                      30   

                                               Unnamed: 2  \
count                                                  50   
unique                                                 43   
top      bt not his girlfrnd... G o o d n i g h t . . .@"   
freq                                                    3   

                   Unnamed: 3 Unnamed: 4  
count                      12          6  
unique                     10          5  
top      MK17 92H. 450Ppw 16"    GNT:-)"  
freq                        2          2



Percentage of missing values: 


v1             0.000000
v2             0.000000
Unnamed: 2    99.102656
Unnamed: 3    99.784637
Unnamed: 4    99.892319
dtype: float64



Infos
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


None

In [ ]:
dataset = dataset.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'])
dataset.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
dataset['v1'] = dataset['v1'].apply(lambda x: 0 if x == 'ham' else 1)
dataset.head()

v1                                                 v2
0   0  Go until jurong point, crazy.. Available only ...
1   0                      Ok lar... Joking wif u oni...
2   1  Free entry in 2 a wkly comp to win FA Cup fina...
3   0  U dun say so early hor... U c already then say...
4   0  Nah I don't think he goes to usf, he lives aro...

In [ ]:
import en_core_web_md
nlp = en_core_web_md.load()

In [ ]:
# Import Stop words 
from spacy.lang.en.stop_words import STOP_WORDS

In [ ]:

dataset["good_msg"] = dataset["v2"].apply(lambda x:''.join(ch for ch in x if ch.isalnum() or ch==" " or ch=="'"))
dataset["good_msg"] = dataset["good_msg"].apply(lambda x: x.replace(" +"," ").lower().strip())
dataset["good_msg"] = dataset["good_msg"].apply(lambda x: " ".join([token.lemma_ for token in nlp(x) if (token.lemma_ not in STOP_WORDS) and (token.text not in STOP_WORDS)]))
dataset.head()

v1                                                 v2  \
0   0  Go until jurong point, crazy.. Available only ...   
1   0                      Ok lar... Joking wif u oni...   
2   1  Free entry in 2 a wkly comp to win FA Cup fina...   
3   0  U dun say so early hor... U c already then say...   
4   0  Nah I don't think he goes to usf, he lives aro...   

                                            good_msg  
0  jurong point crazy available bugis n great wor...  
1                              ok lar joke wif u oni  
2  free entry 2 wkly comp win fa cup final tkts 2...  
3                                u dun early hor u c  
4                                 nah think usf live

In [ ]:
mask = dataset.good_msg.apply(lambda x: type(x)==str)
mask.value_counts()

True    5572
Name: good_msg, dtype: int64

In [ ]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=1000, oov_token="out_of_vocab") # instanciate the tokenizer
tokenizer.fit_on_texts(dataset.good_msg)
dataset["msg_encoded"] = tokenizer.texts_to_sequences(dataset.good_msg)

In [ ]:
dataset.head()

v1                                                 v2  \
0   0  Go until jurong point, crazy.. Available only ...   
1   0                      Ok lar... Joking wif u oni...   
2   1  Free entry in 2 a wkly comp to win FA Cup fina...   
3   0  U dun say so early hor... U c already then say...   
4   0  Nah I don't think he goes to usf, he lives aro...   

                                            good_msg  \
0  jurong point crazy available bugis n great wor...   
1                              ok lar joke wif u oni   
2  free entry 2 wkly comp win fa cup final tkts 2...   
3                                u dun early hor u c   
4                                 nah think usf live   

                                         msg_encoded  
0  [1, 232, 447, 463, 940, 32, 50, 206, 941, 78, ...  
1                           [8, 195, 464, 290, 2, 1]  
2  [10, 303, 3, 529, 658, 30, 1, 843, 424, 1, 1, ...  
3                            [2, 125, 149, 1, 2, 79]  
4                                [703, 20, 659, 130]

###Train test split

In [ ]:
reviews_pad = tf.keras.preprocessing.sequence.pad_sequences(dataset.msg_encoded, padding="post")

In [ ]:
# Train Test Split
xtrain, xval, ytrain, yval = train_test_split(reviews_pad,dataset.v1, test_size=0.3)

In [ ]:
train = tf.data.Dataset.from_tensor_slices((xtrain, ytrain))
val = tf.data.Dataset.from_tensor_slices((xval, yval))

In [ ]:
train_batch = train.shuffle(len(train)).batch(64)
val_batch = val.shuffle(len(val)).batch(64)

In [ ]:
 # Regardons un batch 
for msg, msg_type in train_batch.take(1):
  print(msg, msg_type)
     

tf.Tensor(
[[  1  65   1 ...   0   0   0]
 [824   1   1 ...   0   0   0]
 [133 117 532 ...   0   0   0]
 ...
 [ 48   1 147 ...   0   0   0]
 [  1   1   1 ...   0   0   0]
 [  2 126   3 ...   0   0   0]], shape=(64, 74), dtype=int32) tf.Tensor(
[1 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0], shape=(64,), dtype=int64)


In [ ]:
vocab_size = tokenizer.num_words
model = tf.keras.Sequential([
                  # Couche d'Input Word Embedding           
                  tf.keras.layers.Embedding(vocab_size+1, 8, input_shape=[msg.shape[1],],name="embedding"),
                  # Gobal average pooling
                  tf.keras.layers.GlobalAveragePooling1D(),

                  # Couche Dense classique
                  tf.keras.layers.Dense(16, activation='relu'),

                  # Couche de sortie avec le nombre de neurones en sortie égale au nombre de classe avec fonction softmax
                  tf.keras.layers.Dense(1, activation="sigmoid")
])
     


In [ ]:
model.summary()
     

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 74, 8)             8008      
                                                                 
 global_average_pooling1d_1   (None, 8)                0         
 (GlobalAveragePooling1D)                                        
                                                                 
 dense_2 (Dense)             (None, 16)                144       
                                                                 
 dense_3 (Dense)             (None, 1)                 17        
                                                                 
Total params: 8,169
Trainable params: 8,169
Non-trainable params: 0
_________________________________________________________________


In [ ]:
optimizer= tf.keras.optimizers.Adam()

model.compile(optimizer=optimizer,
              loss=tf.keras.losses.BinaryCrossentropy(),
              metrics=[tf.keras.metrics.BinaryAccuracy
              ()])
     

In [ ]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(64, activation='relu', input_dim=100))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='mean_squared_error',
              metrics=['accuracy'])

model.fit(data, labels, epochs=10, batch_size=32)


In [ ]:
history = model.fit(train_batch, 
                    epochs=50, 
                    validation_data=val_batch)

Epoch 1/50
61/61 [==============================] - 1s 7ms/step - loss: 0.6584 - binary_accuracy: 0.8541 - val_loss: 0.6175 - val_binary_accuracy: 0.8840
Epoch 2/50
61/61 [==============================] - 0s 4ms/step - loss: 0.5798 - binary_accuracy: 0.8582 - val_loss: 0.5199 - val_binary_accuracy: 0.8840
Epoch 3/50
61/61 [==============================] - 0s 4ms/step - loss: 0.4856 - binary_accuracy: 0.8582 - val_loss: 0.4177 - val_binary_accuracy: 0.8840
Epoch 4/50
61/61 [==============================] - 0s 4ms/step - loss: 0.4138 - binary_accuracy: 0.8582 - val_loss: 0.3579 - val_binary_accuracy: 0.8840
Epoch 5/50
61/61 [==============================] - 0s 4ms/step - loss: 0.3812 - binary_accuracy: 0.8582 - val_loss: 0.3328 - val_binary_accuracy: 0.8840
Epoch 6/50
61/61 [==============================] - 0s 4ms/step - loss: 0.3683 - binary_accuracy: 0.8582 - val_loss: 0.3221 - val_binary_accuracy: 0.8840
Epoch 7/50
61/61 [==============================] - 0s 4ms/step - loss: 0.36

In [ ]:
color_chart = ["#4B9AC7", "#4BE8E0", "#9DD4F3", "#97FBF6", "#2A7FAF", "#23B1AB", "#0E3449", "#015955"]

# Visualization of the training process on the loss function
fig = go.Figure(data=[
                      go.Scatter(
                          y=history.history["loss"],
                          name="Training loss",
                          mode="lines",
                          marker=dict(
                          color=color_chart[0]
                          )),
                      go.Scatter(
                          y=history.history["val_loss"],
                          name="Validation loss",
                          mode="lines",
                          marker=dict(
                              color=color_chart[1]
                          ))
])
fig.update_layout(
    title="Training and validation on the loss function",
    xaxis_title="epochs",
    yaxis_title="Cross Entropy"    
)
fig.show()

In [ ]:
# Visualization of accuracy training 
fig = go.Figure(data=[
                      go.Scatter(
                          y=history.history["binary_accuracy"],
                          name="Training accuracy",
                          mode="lines",
                          marker=dict(
                              color=color_chart[0]
                          )),
                      go.Scatter(
                          y=history.history["val_binary_accuracy"],
                          name="Validation accuracy",
                          mode="lines",
                          marker=dict(
                              color=color_chart[1]
                          ))
])
fig.update_layout(
    title="Training and Validation Accuracy",
    xaxis_title="epochs",
    yaxis_title="Accuracy"    
)
fig.show()
     
